server:
  port: 8080

logging:
  level:
    root: INFO
  file:
    name: /app/logs/myapp.log

management:
  endpoints:
    web:
      exposure:
        include: health   # 운영환경은 health만 노출

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/mydb
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}